### ISSUE TITLE
office gpu tensorflw ok,but  this version gpu error:

### ISSUE THREAD

**Issue by zdx3578** [zdx3578/tensorflow.aws.gpu.capa3.0#1]
ubuntu@ip-172-30-0-107:~/worklogdir/aws/shell$ sh startstyle.sh  kk/psb1.jpeg qbs2.jpg 100
/sbin/ldconfig.real: /usr/local/cuda/lib64/libcudnn.so.6.5 is not a symbolic link

/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "neural_style.py", line 153, in <module>
    main()
  File "neural_style.py", line 85, in main
    content_image = imread(options.content)
  File "neural_style.py", line 144, in imread
    return scipy.misc.imread(path).astype(np.float)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/PIL/Image.py", line 512, in **getattr**
    raise AttributeError(name)
AttributeError: **float**

**Comment by zdx3578** [comment]
i am runing this  https://github.com/anishathalye/neural-style/

**Comment by zdx3578** [comment]
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-e191b38b  
http://ramhiser.com/2016/01/05/installing-tensorflow-on-an-aws-ec2-instance-with-gpu-support/  he provide a image in aws
